build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --bootstrap tests/Bootstrap.php --configuration phpunit.xml tests/src/
            coverage:
              file: tests/nb-phpunit-coverage.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }


